### ISSUE TITLE
Spacer M2 5mm -> Threaded M2 Spacer 5mm

### ISSUE THREAD

**Issue by zxku** [beekeeb/Allium58#4]
I was confused about how you put this thing together until I realized that the brass spacers you specify for use are threaded.  Typically the term "M2 spacer" would refer to an unthreaded tube who's inner diameter is selected to slide over the outer diameter of an M2 screw.  A _threaded_ M2 spacer, is the term. to describe a tube with a threaded hole through the center.

I would recommend at least changing the documentation to "Threaded M2 spacer" to avoid confusion. 

_In this case, I think that would be good enough to avoid confusion, which is the important part.  However the technically correct terminology would actually call it a female threaded spacer, and should also specify the thread pitch in addition to the thread diameter and length._  They are also sometimes specified as a female threaded tube.

**Comment by torytang** [comment]
Thank you @zxku :) 

I updated the readme.
